
  # Authentication method: 'uuid' or 'nickname'
  auth:
    method: uuid

  # Database configuration
  database:
    type: sqlite
    sqlite:
      file: authcraft.db
    postgresql:
      host: localhost
      port: 5432
      database: authcraft
      username: authcraft
      password: password
      pool_size: 10

  # Cloudflare Warp settings
  cloudflare_warp:
    mode: any  # Options: required, disabled, any

  # Telegram bot configuration
  telegram:
    token: your_telegram_bot_token

  # VK bot configuration
  vk:
    token: your_vk_bot_token

  # Encryption key for 2FA secrets
  encryption:
    key: your_encryption_key

  # Connection limit per IP
  connection_limit: 3

  # Language for messages (en or ru)
  language: en

  # Role system settings
  roles:
    default: player
