package com.httydcraft.authcraft.core.database.type;

import com.google.common.flogger.GoogleLogger;
import com.j256.ormlite.field.FieldType;
import com.j256.ormlite.jdbc.db.PostgresDatabaseType;

import java.util.List;

// #region Class Documentation
/**
 * Custom PostgreSQL database type supporting identity columns.
 * Overrides behavior for versions prior to PostgreSQL 10.
 */
public class IdentityPostgresDatabaseType extends PostgresDatabaseType {
    private static final GoogleLogger LOGGER = GoogleLogger.forEnclosingClass();
    // #endregion

    // #region Sequence Configuration
    /**
     * Determines if an ID sequence is needed based on the driver version.
     *
     * @return {@code true} if the driver version is less than 10, {@code false} otherwise.
     */
    @Override
    public boolean isIdSequenceNeeded() {
        boolean needed = driver.getMajorVersion() < 10;
        LOGGER.atFine().log("Checked ID sequence needed: %b (driver version: %d)", needed, driver.getMajorVersion());
        return needed;
    }
    // #endregion

    // #region ID Configuration
    /**
     * Configures the generated ID column for the table.
     *
     * @param tableName       The table name.
     * @param sb              The string builder for the SQL statement.
     * @param fieldType       The field type.
     * @param statementsBefore Statements to execute before.
     * @param statementsAfter  Statements to execute after.
     * @param additionalArgs   Additional arguments.
     * @param queriesAfter     Queries to execute after.
     */
    @Override
    protected void configureGeneratedId(String tableName, StringBuilder sb, FieldType fieldType,
                                        List<String> statementsBefore, List<String> statementsAfter,
                                        List<String> additionalArgs, List<String> queriesAfter) {
        if (fieldType.isAllowGeneratedIdInsert()) {
            sb.append("GENERATED BY DEFAULT AS IDENTITY ");
            LOGGER.atFine().log("Configured generated ID for table %s: BY DEFAULT", tableName);
        } else {
            sb.append("GENERATED ALWAYS AS IDENTITY ");
            LOGGER.atFine().log("Configured generated ID for table %s: ALWAYS", tableName);
        }
        configureId(sb, fieldType, statementsBefore, additionalArgs, queriesAfter);
    }
    // #endregion
}